# ansible/inventory/group_vars/poc_docker_hosts.yml
# Variables for POC Docker Hosts

poc_project_path: "/home/ave/berca-poc-store"
log_dir_path: "{{ poc_project_path }}/docker/log-saturation/data"
log_file_path: "{{ log_dir_path }}/app-saturation.log"
trigger_file_path: "{{ log_dir_path }}/.trigger_saturation"

pgbouncer_host: "pgbouncer"
pgbouncer_port: 6432
pgbouncer_admin_user: "postgres"
pgbouncer_db: "pgbouncer"
pgbouncer_target_db: "medusa-store"

target_pool_size: 25
target_max_connections: 25
baseline_pool_size: 5
baseline_max_connections: 5
target_disk_max_pct: 10
