init_config:

instances:
  - name: poc-berca-backend-health
    url: http://medusa:9000/demo/backend-health
    timeout: 3
    min_collection_interval: 5
    tags:
      - env:poc
      - service:berca-backend
      - capability:backend
